// Fallback for bun < 1.4.2, which has no `bun build --compile --asset <dir>` flag
// (see docs/decisions/0001-bun-version.md). `--asset` fails SILENTLY on those
// versions — bun drops the unrecognised flag and misparses the following path
// as an entry point — so this script exists to embed the Vite build a different
// way: one explicit `import x from "<file>" with { type: "file" }` per dist
// file, each one referenced at runtime via ASSET_PATHS. An import that isn't
// referenced is dropped by dead-code elimination, so this generated module and
// the map it exports must both be consumed — src/server/routes.ts is the
// consumer (loadAssets() reads every entry into a Map of Bun.file(diskPath),
// which serveAsset() serves from). It was src/skeleton.ts until Task 4 deleted
// that file; the stale name sat here through three more tasks, which is why
// this one names the function as well as the module.
//
// Regenerate before every `--compile` build: `bun run scripts/gen-assets.ts`.
import { existsSync, readdirSync, writeFileSync } from 'node:fs'
import { join, relative, dirname } from 'node:path'

// `--allow-empty` is filtered out of the positionals rather than counted in
// them: `bun run scripts/gen-assets.ts --allow-empty` must still mean "default
// DIST, default OUT", and process.argv[2] would otherwise be the flag itself.
const args = process.argv.slice(2)
const ALLOW_EMPTY = args.includes('--allow-empty')
const positional = args.filter(a => !a.startsWith('--'))
const DIST = positional[0] ?? './web-dist'
const OUT = positional[1] ?? './src/generated-assets.ts'

function walk(dir: string): string[] {
  let out: string[] = []
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, e.name)
    out = e.isDirectory() ? out.concat(walk(full)) : out.concat(full)
  }
  return out
}

// A MISSING ./web-dist is the same case as an empty one. web-dist is
// gitignored, so on a fresh clone readdirSync threw ENOENT with a stack trace
// and the friendly message below could only ever fire for an
// existing-but-empty directory — the half that never happens in practice.
const files = existsSync(DIST) ? walk(DIST).sort() : []
if (files.length === 0 && !ALLOW_EMPTY) {
  console.error(`gen-assets: no files found under ${DIST} — did you run the vite build first? (bun run build:web)`)
  process.exit(1)
}

const outDir = dirname(OUT)
const imports: string[] = []
const entries: string[] = []

files.forEach((file, i) => {
  const urlPath = '/' + relative(DIST, file).split('\\').join('/')
  const rel = relative(outDir, file).split('\\').join('/')
  const importPath = rel.startsWith('.') ? rel : `./${rel}`
  const varName = `asset${i}`
  imports.push(`import ${varName} from '${importPath}' with { type: 'file' }`)
  entries.push(`  ${JSON.stringify(urlPath)}: ${varName},`)
})

const body = `// AUTO-GENERATED by scripts/gen-assets.ts — do not edit by hand.
// Regenerate with: bun run scripts/gen-assets.ts
//
// @ts-nocheck bun-types' \`declare module "*" with { type: "file" }\` (which
// types every such import as \`string\`) only resolves under TypeScript 7.1's
// newer import-attribute-first module resolution. This repo's TypeScript 5.x
// falls back to extension-based ambient declarations instead (\`*.html\` typed
// as HTMLBundle, \`*.css\`/\`*.js\` untyped), which misdescribes these imports
// even though bun's bundler resolves the "file" loader correctly at runtime —
// verified by the Step 8 packaging assertion actually serving the content.
${imports.join('\n')}

// Each import above resolves (at compile time, inside --compile) to a virtual
// /$bunfs path string for the embedded file; ASSET_PATHS maps the original
// dist-relative URL path to that string so the server can do
// \`Bun.file(ASSET_PATHS[path])\`. Referencing every entry here is what keeps
// dead-code elimination from dropping the import.
export const ASSET_PATHS: Record<string, string> = {
${entries.join('\n')}
}
`

writeFileSync(OUT, body)
if (files.length === 0) {
  // Reached only under --allow-empty. `tsc --noEmit` needs this module to
  // exist at all (src/server/routes.ts:32 imports it), so typecheck writes a
  // stub rather than skipping generation. build:server keeps the hard failure
  // above, and assert:package remains the end-to-end proof that a real build
  // embedded real bytes.
  console.error(`gen-assets: ${DIST} is missing or empty; wrote a stub manifest for typecheck only — this build serves no assets.`)
}
console.log(`gen-assets: wrote ${files.length} entries to ${OUT}`)
